use std::{
    env,
    fmt::Write as _,
    fs,
    path::{Path, PathBuf},
};

#[derive(Debug)]
struct MigrationFile {
    version: i64,
    name: String,
    file_name: String,
}

fn main() {
    println!("cargo::rerun-if-changed=migrations");

    let manifest_dir = PathBuf::from(
        env::var_os("CARGO_MANIFEST_DIR").expect("Cargo must set CARGO_MANIFEST_DIR"),
    );
    let migrations_dir = manifest_dir.join("migrations");
    let migrations = discover_migrations(&migrations_dir)
        .unwrap_or_else(|error| panic!("invalid migration catalog: {error}"));
    let generated = render_catalog(&migrations);
    let output = PathBuf::from(env::var_os("OUT_DIR").expect("Cargo must set OUT_DIR"))
        .join("migrations.rs");
    fs::write(&output, generated)
        .unwrap_or_else(|error| panic!("failed to write {}: {error}", output.display()));
}

fn discover_migrations(directory: &Path) -> Result<Vec<MigrationFile>, String> {
    let entries = fs::read_dir(directory)
        .map_err(|error| format!("failed to read {}: {error}", directory.display()))?;
    let mut migrations = Vec::new();

    for entry in entries {
        let entry = entry.map_err(|error| {
            format!(
                "failed to inspect a file in {}: {error}",
                directory.display()
            )
        })?;
        let path = entry.path();
        if path.extension().and_then(|extension| extension.to_str()) != Some("sql") {
            continue;
        }
        if !entry
            .file_type()
            .map_err(|error| format!("failed to inspect {}: {error}", path.display()))?
            .is_file()
        {
            return Err(format!("{} is not a regular file", path.display()));
        }

        let file_name = entry
            .file_name()
            .into_string()
            .map_err(|_| format!("{} has a non-UTF-8 filename", path.display()))?;
        let name = path
            .file_stem()
            .and_then(|stem| stem.to_str())
            .ok_or_else(|| format!("{} has a non-UTF-8 filename", path.display()))?
            .to_owned();
        let (prefix, description) = name
            .split_once('_')
            .ok_or_else(|| format!("{file_name} must be named like 0001_description.sql"))?;
        if prefix.len() != 4
            || !prefix.bytes().all(|character| character.is_ascii_digit())
            || description.is_empty()
        {
            return Err(format!(
                "{file_name} must be named like 0001_description.sql"
            ));
        }
        let version = prefix
            .parse::<i64>()
            .map_err(|error| format!("invalid version in {file_name}: {error}"))?;
        if version == 0 {
            return Err(format!("{file_name} must start at version 0001"));
        }
        migrations.push(MigrationFile {
            version,
            name,
            file_name,
        });
    }

    migrations.sort_by_key(|migration| migration.version);
    if migrations.is_empty() {
        return Err("at least one .sql migration file is required".to_owned());
    }
    for (index, migration) in migrations.iter().enumerate() {
        let expected = i64::try_from(index + 1)
            .map_err(|_| "migration count exceeds supported numeric versions".to_owned())?;
        if migration.version < expected {
            return Err(format!(
                "duplicate migration version {:04} in {}",
                migration.version, migration.file_name
            ));
        }
        if migration.version > expected {
            return Err(format!(
                "migration versions must be contiguous: expected {:04}, found {:04} in {}",
                expected, migration.version, migration.file_name
            ));
        }
    }

    Ok(migrations)
}

fn render_catalog(migrations: &[MigrationFile]) -> String {
    let mut output = String::from("// Generated by build.rs. Do not edit.\n");
    output.push_str("const MIGRATIONS: &[Migration] = &[\n");
    for migration in migrations {
        writeln!(
            output,
            "    Migration {{ version: {}, name: {:?}, sql: include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/migrations/\", {:?})) }},",
            migration.version, migration.name, migration.file_name
        )
        .expect("writing to a String cannot fail");
    }
    output.push_str("];\n");
    writeln!(
        output,
        "const LATEST_SCHEMA_VERSION: i64 = {};",
        migrations
            .last()
            .expect("migration catalog is non-empty")
            .version
    )
    .expect("writing to a String cannot fail");
    output
}
